### ISSUE TITLE
Spack script failed on invocation of spack

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/aws-parallelcluster-post-install-scripts#8]
Cluster creation succeeds however when I run `spack` I get:

```
[ec2-user@ip-172-31-33-190 ~]$ spack
==> Error: /shared/spack/etc/spack/config.yaml:1: Additional properties are not allowed (404 was unexpected)
```

**Comment by stephenmsachs** [comment]
This error happens when the content of a file (in this case `config.yaml`) is "Error 404". This can happen when there is a mismatch of the versions of `postinstall.sh` and the rest of the https://github.com/spack/spack-configs repo. `config.yaml` was removed from the repo here https://github.com/spack/spack-configs/commit/e98a69c541413978de5d3e07fcccc133302e06c2.
